spring:
  application:
    name: dataway2
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    format:
      dateTime: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://39.98.181.90:3306/dataway2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: dataway2
    password: '$%3f6T48'
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: 39.98.181.90
      database: dataway2
      username: dataway2
      password: '$%3f6T48'
      port: 27017

logging:
  level:
    com.github.alenfive.dataway2: debug

